# Generated by Django 3.0.4 on 2020-03-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=200)),
                ('ram', models.IntegerField()),
                ('storage', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('os', models.CharField(max_length=20)),
                ('battery', models.IntegerField()),
                ('displayrefreshrate', models.IntegerField()),
                ('cable', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
    ]
