# Generated by Django 3.0.4 on 2020-03-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200312_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='cable',
            field=models.CharField(max_length=30),
        ),
    ]
