# Generated by Django 3.0.4 on 2020-03-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('ram', models.IntegerField(null=True)),
                ('storage', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=20, null=True)),
                ('os', models.CharField(max_length=20, null=True)),
                ('battery', models.IntegerField(null=True)),
                ('displayrefreshrate', models.IntegerField(null=True)),
                ('cable', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
