# Generated by Django 3.0.4 on 2020-03-16 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerforms', '0002_auto_20200316_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdata',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerdata',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
