# Generated by Django 3.0.4 on 2020-03-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerforms', '0003_auto_20200316_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerdata',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sellerdata',
            name='frontcam',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sellerdata',
            name='modelname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sellerdata',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sellerdata',
            name='rearcam',
            field=models.IntegerField(null=True),
        ),
    ]
