# Generated by Django 3.0.4 on 2020-04-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerforms', '0004_auto_20200316_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerdata',
            name='photo_1',
            field=models.ImageField(blank=True, default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerdata',
            name='photo_2',
            field=models.ImageField(blank=True, default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerdata',
            name='photo_3',
            field=models.ImageField(blank=True, default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerdata',
            name='photo_4',
            field=models.ImageField(blank=True, default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerdata',
            name='photo_5',
            field=models.ImageField(blank=True, default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerdata',
            name='photo_6',
            field=models.ImageField(blank=True, default=1, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerdata',
            name='photo_main',
            field=models.ImageField(default=1, upload_to='photos/%Y%m/%d/'),
            preserve_default=False,
        ),
    ]
